/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ralaokdtcqtkeejlykcg"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJhbGFva2R0Y3F0a2Vlamx5a2NnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1OTIwMDEsImV4cCI6MjA2ODE2ODAwMX0.P8r4ecJrR-sJur4X-ZHe9SYnNkgXVR9SYUsREXoFv-Q"